# app/services/irs_auth_service.py
"""
Business logic for IRS authorization forms (8821 and 2848).

PDF generation produces a clearly-marked stub PDF using weasyprint.
A real pre-filled IRS form requires IRS e-Services credentials
obtained post-launch. The stub contains all client and firm data
so the end-to-end flow is fully testable.
"""

import io
import uuid
from datetime import date, datetime, timezone
from typing import Optional

from sqlalchemy import select
from sqlalchemy.orm import Session
from uuid import UUID

from app.crud import irs_authorization as crud_auth
from app.crud import signature_envelope as crud_envelope
from app.models.client import Client
from app.models.firm import Firm
from app.schemas.irs_authorization import (
    IrsAuthorizationCreate,
    IrsAuthorizationSendRequest,
    IrsAuthorizationUpdate,
)
from app.schemas.signature_envelope import SignatureEnvelopeCreate
from app.services import s3 as s3_service
from app.services.audit_service import write_audit_log
from app.services.behavioral_log import log_event


FORM_DESCRIPTIONS = {
    "8821": "Tax Information Authorization",
    "2848": "Power of Attorney and Declaration of Representative",
}


def generate_auth_stub_pdf(
    firm: Firm,
    client: Client,
    form_type: str,
    tax_years: list[int],
    valid_from: Optional[date],
    valid_until: Optional[date],
) -> bytes:
    """Generate a stub PDF for the IRS authorization form."""
    form_name = FORM_DESCRIPTIONS.get(form_type, f"IRS Form {form_type}")
    years_str = ", ".join(str(y) for y in sorted(tax_years)) if tax_years else "Not specified"
    valid_from_str = valid_from.isoformat() if valid_from else "Effective immediately"
    valid_until_str = valid_until.isoformat() if valid_until else "Indefinite"
    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    logo_url = None
    firm_settings = firm.settings or {} if firm.settings else {}
    s3_key = firm_settings.get("portal_logo_s3_key")
    if s3_key:
        try:
            from app.services.s3 import generate_presigned_url
            logo_url = generate_presigned_url(s3_key)
        except Exception:
            pass

    logo_block = (
        f'<img src="{logo_url}" style="max-height:50px;width:auto;'
        f'display:block;margin-bottom:8px;" />'
        if logo_url else
        f'<h1>{firm.name}</h1>'
    )

    html = f"""<!DOCTYPE html>
<html><head><meta charset="utf-8">
<style>
  body {{ font-family: Arial, sans-serif; font-size: 12px; margin: 40px; color: #111111; }}
  h1 {{ font-size: 18px; font-weight: bold; margin-bottom: 4px; }}
  h2 {{ font-size: 14px; font-weight: bold; margin-top: 24px; margin-bottom: 8px;
        border-bottom: 1px solid #C8CDD6; padding-bottom: 4px; }}
  .stub-banner {{ background: #FEF3C7; border: 1px solid #F59E0B; padding: 10px 16px;
                  border-radius: 6px; margin-bottom: 24px; font-size: 11px; color: #92400E; }}
  table {{ width: 100%; border-collapse: collapse; margin-bottom: 16px; }}
  td {{ padding: 6px 8px; vertical-align: top; }}
  td:first-child {{ font-weight: bold; width: 40%; color: #6B7280; }}
  .sig-block {{ border: 1px solid #C8CDD6; padding: 16px; border-radius: 6px; margin-top: 32px; }}
  .sig-line {{ border-bottom: 1px solid #111111; margin-top: 32px; margin-bottom: 4px; }}
  .footer {{ margin-top: 40px; font-size: 10px; color: #9CA3AF; }}
</style></head>
<body>
  {logo_block}
  <h2 style="margin-top:4px;">IRS Form {form_type} — {form_name}</h2>
  <p style="color:#6B7280;font-size:11px;">Prepared by JAMM PX · {generated_at}</p>
  <div class="stub-banner">
    &#9888; STUB DOCUMENT — Review all information below before signing.
    The final IRS-formatted form will be submitted after signature collection.
  </div>
  <h2>Taxpayer Information</h2>
  <table>
    <tr><td>Name</td><td>{client.name}</td></tr>
    <tr><td>Primary Email</td><td>{getattr(client, 'primary_email', None) or 'Not on file'}</td></tr>
  </table>
  <h2>Representative (Firm)</h2>
  <table>
    <tr><td>Firm Name</td><td>{firm.name}</td></tr>
  </table>
  <h2>Authorization Details</h2>
  <table>
    <tr><td>Form Type</td><td>Form {form_type} — {form_name}</td></tr>
    <tr><td>Tax Years Covered</td><td>{years_str}</td></tr>
    <tr><td>Effective From</td><td>{valid_from_str}</td></tr>
    <tr><td>Expires</td><td>{valid_until_str}</td></tr>
  </table>
  <div class="sig-block">
    <p><strong>Taxpayer Signature</strong></p>
    <p style="font-size:11px;color:#6B7280;">
      By signing, I authorize the firm named above to act on my behalf
      as described in IRS Form {form_type}.
    </p>
    <div class="sig-line"></div>
    <p style="font-size:11px;">Signature &nbsp;&nbsp;&nbsp; Date _______________</p>
  </div>
  <div class="footer">Generated by JAMM PX Practice Management Platform.</div>
</body></html>"""

    try:
        import weasyprint
        return weasyprint.HTML(string=html).write_pdf()
    except Exception:
        return html.encode("utf-8")


def send_irs_authorization(
    db: Session,
    request: IrsAuthorizationSendRequest,
    firm: Firm,
    client: Client,
    sent_by_user_id: uuid.UUID,
) -> dict:
    """
    Full send flow for an IRS authorization form.
    Returns: {"authorization": IrsAuthorization, "envelope": SignatureEnvelope}
    """
    # 1. Generate PDF
    pdf_bytes = generate_auth_stub_pdf(
        firm=firm,
        client=client,
        form_type=request.form_type,
        tax_years=request.tax_years,
        valid_from=request.valid_from,
        valid_until=request.valid_until,
    )

    # 2. Upload to S3
    file_key = f"{firm.id}/{client.id}/irs-auth/{request.form_type}-{uuid.uuid4()}.pdf"
    try:
        s3_service.upload_fileobj(
            fileobj=io.BytesIO(pdf_bytes),
            s3_key=file_key,
            content_type="application/pdf",
        )
    except Exception:
        file_key = f"stub/{firm.id}/{request.form_type}-pending.pdf"

    # 3. Create IrsAuthorization record
    auth_create = IrsAuthorizationCreate(
        client_id=client.id,
        form_type=request.form_type,
        tax_years=request.tax_years,
        valid_from=request.valid_from,
        valid_until=request.valid_until,
    )
    authorization = crud_auth.create_irs_authorization(
        db=db, auth_in=auth_create, firm_id=firm.id
    )

    # Log authorization created
    log_event(
        firm_id=authorization.firm_id,
        event_type="irs_authorization.created",
        entity_type="irs_authorization",
        entity_id=authorization.id,
        actor_type="staff",
        actor_id=sent_by_user_id,
        metadata={
            "form_type": str(authorization.form_type) if hasattr(authorization, 'form_type') and authorization.form_type else None,
            "expiry_date": authorization.expiry_date.isoformat() if hasattr(authorization, 'expiry_date') and authorization.expiry_date else None,
            "client_id": str(authorization.client_id) if hasattr(authorization, 'client_id') else None,
        }
    )

    # 5. Create SignatureEnvelope
    form_description = FORM_DESCRIPTIONS.get(request.form_type, f"IRS Form {request.form_type}")
    signer_email = getattr(client, "primary_email", None) or ""

    envelope_create = SignatureEnvelopeCreate(
        client_id=client.id,
        engagement_id=None,
        document_id=None,
        signers=[{"name": client.name, "email": signer_email, "status": "pending"}],
        subject=f"Please sign: IRS Form {request.form_type} — {form_description}",
        message=(
            f"{firm.name} is requesting your signature on "
            f"IRS Form {request.form_type} ({form_description})."
        ),
    )
    envelope = crud_envelope.create_signature_envelope(
        db=db, schema=envelope_create, firm_id=firm.id
    )

    # 6. Link envelope to authorization
    crud_auth.update_irs_authorization(
        db=db,
        auth=authorization,
        auth_in=IrsAuthorizationUpdate(signature_envelope_id=envelope.id),
    )

    # 7. Attempt Dropbox Sign send (graceful failure)
    try:
        from app.services import dropbox_sign
        dropbox_sign.send_signature_request(
            envelope_id=str(envelope.id),
            signers=[{"name": client.name, "email_address": signer_email}],
            file_bytes=pdf_bytes,
            subject=envelope_create.subject,
            message=envelope_create.message or "",
        )
    except Exception:
        pass  # Credentials not configured — envelope stays draft

    # 8. Audit log
    write_audit_log(
        db=db,
        firm_id=firm.id,
        actor_id=sent_by_user_id,
        action=f"irs_authorization.sent.{request.form_type}",
        entity_type="irs_authorization",
        entity_id=authorization.id,
    )

    return {
        "authorization": authorization,
        "envelope": envelope,
    }


def check_expiring_authorizations() -> dict:
    """
    Scheduler function: find active authorizations expiring within 30 days
    and emit irs_authorization.expiry_approaching events.
    Creates its own DB session. Safe to call from background tasks.
    """
    from app.db.session import SessionLocal
    from app.services.event_bus import emit_event_sync
    from app.core.enums import TriggerEvent

    db = SessionLocal()
    try:
        expiring = crud_auth.get_authorizations_expiring_soon(db, days=30)
        alerts_emitted = 0

        for auth in expiring:
            days_remaining = (auth.valid_until - date.today()).days
            emit_event_sync(
                event=TriggerEvent.irs_authorization_expiry_approaching,
                payload={
                    "firm_id": str(auth.firm_id),
                    "client_id": str(auth.client_id),
                    "authorization_id": str(auth.id),
                    "form_type": auth.form_type,
                    "valid_until": auth.valid_until.isoformat(),
                    "days_remaining": days_remaining,
                },
            )
            crud_auth.update_irs_authorization(
                db=db,
                auth=auth,
                auth_in=IrsAuthorizationUpdate(expiry_notification_sent=True),
            )
            log_event(
                firm_id=auth.firm_id,
                event_type="irs_authorization.expiry_warning_sent",
                entity_type="irs_authorization",
                entity_id=auth.id,
                actor_type="system",
                actor_id=None,
                metadata={
                    "days_until_expiry": days_remaining,
                    "warning_tier": None,
                }
            )
            if auth.valid_until is not None and auth.valid_until < date.today():
                mark_authorization_expired(
                    db=db,
                    authorization=auth,
                    firm_id=auth.firm_id,
                )
            alerts_emitted += 1

        return {"checked": len(expiring), "alerts_emitted": alerts_emitted}
    finally:
        db.close()


def mark_authorization_renewed(
    *,
    db: Session,
    authorization,
    firm_id,
    actor_id=None,
) -> None:
    log_event(
        firm_id=firm_id,
        event_type="irs_authorization.renewed",
        entity_type="irs_authorization",
        entity_id=authorization.id,
        actor_type="system",
        actor_id=actor_id,
        metadata={
            "form_type": str(authorization.form_type) if hasattr(authorization, "form_type") and authorization.form_type else None,
            "new_expiry_date": authorization.valid_until.isoformat() if hasattr(authorization, "valid_until") and authorization.valid_until else None,
            "client_id": str(authorization.client_id) if hasattr(authorization, "client_id") else None,
        }
    )


def mark_authorization_expired(
    *,
    db: Session,
    authorization,
    firm_id,
) -> None:
    log_event(
        firm_id=firm_id,
        event_type="irs_authorization.expired",
        entity_type="irs_authorization",
        entity_id=authorization.id,
        actor_type="system",
        actor_id=None,
        metadata={
            "form_type": str(authorization.form_type) if hasattr(authorization, "form_type") and authorization.form_type else None,
            "expired_date": authorization.valid_until.isoformat() if hasattr(authorization, "valid_until") and authorization.valid_until else None,
            "client_id": str(authorization.client_id) if hasattr(authorization, "client_id") else None,
            "days_since_expiry_warning": None,
        }
    )


def activate_authorization_for_envelope(
    *,
    db: Session,
    envelope_id: UUID,
    firm_id: UUID,
) -> None:
    """
    Called when a signature envelope is signed. If that envelope is an IRS
    authorization form, flip the linked IrsAuthorization from
    pending_signature to active and fire the behavioral event. No-op if the
    envelope is not linked to an authorization (the common case for plain
    engagement letters).
    """
    from app.models.irs_authorization import IrsAuthorization

    auth = db.execute(
        select(IrsAuthorization).where(
            IrsAuthorization.signature_envelope_id == envelope_id,
            IrsAuthorization.firm_id == firm_id,
        )
    ).scalar_one_or_none()

    if auth is None:
        return

    old_status = auth.status
    if old_status != "pending_signature":
        return

    auth.status = "active"
    if auth.valid_from is None:
        auth.valid_from = date.today()
    db.commit()

    log_event(
        firm_id=firm_id,
        event_type="irs_authorization.activated",
        entity_type="irs_authorization",
        entity_id=auth.id,
        actor_type="client",
        actor_id=None,
        metadata={
            "from_status": old_status,
            "to_status": "active",
            "form_type": str(auth.form_type) if auth.form_type else None,
            "client_id": str(auth.client_id),
            "valid_until": auth.valid_until.isoformat() if auth.valid_until else None,
        }
    )
