// path: frontend/src/lib/api/index.ts
export { clientsApi } from './clients'
export { engagementsApi } from './engagements'
export { tasksApi } from './tasks'
export { documentsApi } from './documents'
export { invoicesApi } from './invoices'
export { dashboardApi } from './dashboard'
export { firmChatApi } from './firmChat'
export type { Client, ClientDetail, PaginatedResponse } from './clients'
export type { Engagement } from './engagements'
export type { Task } from './tasks'
export type { Document } from './documents'
export type { Invoice } from './invoices'
export type { DashboardItem, DashboardStats, DashboardMetrics, OverdueEngagementItem, UpcomingDeadlineItem, StaffUtilizationItem, UnsignedDocumentItem } from './dashboard'
export type { Channel, FirmMessage } from './firmChat'
