"""add_metric_registry_table

Revision ID: 1e16e4b22bea
Revises: b6e2a94f7c18
Create Date: 2026-07-09 20:01:34.438657

"""
import uuid
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import insert as pg_insert


# revision identifiers, used by Alembic.
revision: str = '1e16e4b22bea'
down_revision: Union[str, Sequence[str], None] = 'b6e2a94f7c18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Locked Session 0 metric definitions. (key, display_name, unit, better_direction, benchmark_eligible, tier)
SEED_METRICS = [
    ("engagement_velocity", "Engagement Velocity", "days", "lower", True, 1),
    ("deadline_adherence_original", "Deadline Adherence - Beat Original", "percent", "higher", True, 1),
    ("deadline_adherence_extended", "Deadline Adherence - Beat Extended", "percent", "higher", True, 1),
    ("deadline_adherence_operative", "Deadline Adherence - Beat Operative", "percent", "higher", True, 1),
    ("document_collection_speed", "Document Collection Speed", "days", "lower", True, 1),
    ("invoice_payment_time", "Invoice Payment Time", "days", "lower", True, 1),
    ("portal_utilization_documents", "Portal Utilization - Document Items", "percent", "higher", True, 1),
    ("portal_utilization_invoices", "Portal Utilization - Invoice Payments", "percent", "higher", True, 1),
    ("portal_utilization_todos", "Portal Utilization - Todos", "percent", "higher", True, 1),
    ("portal_utilization_esign", "Portal Utilization - E-signatures", "percent", "higher", True, 1),
    ("automation_utilization", "Automation Utilization", "percent", "higher", True, 1),
]


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metric_registry',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('better_direction', sa.Enum('lower', 'higher', name='betterdirection', native_enum=False), nullable=False),
    sa.Column('benchmark_eligible', sa.Boolean(), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metric_registry_key'), 'metric_registry', ['key'], unique=True)
    # ### end Alembic commands ###

    metric_registry = sa.table(
        'metric_registry',
        sa.column('id', sa.UUID()),
        sa.column('key', sa.String()),
        sa.column('display_name', sa.String()),
        sa.column('unit', sa.String()),
        sa.column('better_direction', sa.String()),
        sa.column('benchmark_eligible', sa.Boolean()),
        sa.column('tier', sa.Integer()),
        sa.column('is_active', sa.Boolean()),
    )

    connection = op.get_bind()
    for key, display_name, unit, better_direction, benchmark_eligible, tier in SEED_METRICS:
        stmt = pg_insert(metric_registry).values(
            id=uuid.uuid4(),
            key=key,
            display_name=display_name,
            unit=unit,
            better_direction=better_direction,
            benchmark_eligible=benchmark_eligible,
            tier=tier,
            is_active=True,
        ).on_conflict_do_nothing(index_elements=['key'])
        connection.execute(stmt)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_metric_registry_key'), table_name='metric_registry')
    op.drop_table('metric_registry')
    # ### end Alembic commands ###
