"""add_audit_logs

Revision ID: 4e5c69ee809d
Revises: 0037_add_concierge_question_log_and_notifications
Create Date: 2026-05-29 09:48:15.241393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e5c69ee809d'
down_revision: Union[str, Sequence[str], None] = '0037_add_concierge_question_log_and_notifications'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('firm_id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('actor_type', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=200), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=True),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_audit_logs_firm_id'), 'audit_logs', ['firm_id'], unique=False, if_not_exists=True)
    op.alter_column('clients', 'firm_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('clients', 'entity_type',
               existing_type=sa.VARCHAR(length=20),
               comment='individual | business | trust | estate',
               existing_nullable=True)
    op.drop_index('ix_clients_entity_type', table_name='clients')
    op.alter_column('contacts', 'firm_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index('ix_audit_logs_document_id', table_name='document_audit_logs')
    op.drop_index('ix_audit_logs_firm_id', table_name='document_audit_logs')
    op.drop_index('ix_audit_logs_user_id', table_name='document_audit_logs')
    op.drop_index('ix_documents_category', table_name='documents')
    op.drop_index('ix_engagement_templates_is_recurring', table_name='engagement_templates')
    op.alter_column('engagements', 'firm_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('engagements', 'filing_deadline',
               existing_type=sa.DATE(),
               comment='IRS filing deadline. Auto-set from engagement_type on creation. Use extended_deadline instead if an extension has been filed.',
               existing_nullable=True)
    op.alter_column('engagements', 'extended_deadline',
               existing_type=sa.DATE(),
               comment='Extended IRS deadline after extension filing. This field overrides filing_deadline in all scheduler checks.',
               existing_nullable=True)
    op.drop_index('ix_engagements_filing_deadline', table_name='engagements')
    op.drop_constraint('firms_slug_key', 'firms', type_='unique')
    op.drop_index('ix_irs_authorizations_status', table_name='irs_authorizations')
    op.drop_constraint('uq_portal_sessions_magic_link_token_hash', 'portal_sessions', type_='unique')
    op.drop_index('ix_portal_sessions_magic_link_token_hash', table_name='portal_sessions')
    op.create_index(op.f('ix_portal_sessions_magic_link_token_hash'), 'portal_sessions', ['magic_link_token_hash'], unique=True)
    op.drop_constraint('stripe_connections_firm_id_key', 'stripe_connections', type_='unique')
    op.drop_index('ix_stripe_connections_firm_id', table_name='stripe_connections')
    op.create_index(op.f('ix_stripe_connections_firm_id'), 'stripe_connections', ['firm_id'], unique=True)
    op.alter_column('tasks', 'firm_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('tax_organizer_templates', 'is_default',
               existing_type=sa.BOOLEAN(),
               comment='True for the three seeded templates. Firms can still edit them.',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('tax_organizer_templates', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='False for soft-deleted templates.',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_index('ix_transcript_requests_status', table_name='transcript_requests')
    op.alter_column('users', 'firm_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'firm_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index('ix_transcript_requests_status', 'transcript_requests', ['status'], unique=False)
    op.alter_column('tax_organizer_templates', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='False for soft-deleted templates.',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('tax_organizer_templates', 'is_default',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='True for the three seeded templates. Firms can still edit them.',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('tasks', 'firm_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('ix_stripe_connections_firm_id'), table_name='stripe_connections')
    op.create_index('ix_stripe_connections_firm_id', 'stripe_connections', ['firm_id'], unique=False)
    op.create_unique_constraint('stripe_connections_firm_id_key', 'stripe_connections', ['firm_id'])
    op.drop_index(op.f('ix_portal_sessions_magic_link_token_hash'), table_name='portal_sessions')
    op.create_index('ix_portal_sessions_magic_link_token_hash', 'portal_sessions', ['magic_link_token_hash'], unique=False)
    op.create_unique_constraint('uq_portal_sessions_magic_link_token_hash', 'portal_sessions', ['magic_link_token_hash'])
    op.create_index('ix_irs_authorizations_status', 'irs_authorizations', ['status'], unique=False)
    op.create_unique_constraint('firms_slug_key', 'firms', ['slug'])
    op.create_index('ix_engagements_filing_deadline', 'engagements', ['filing_deadline'], unique=False)
    op.alter_column('engagements', 'extended_deadline',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Extended IRS deadline after extension filing. This field overrides filing_deadline in all scheduler checks.',
               existing_nullable=True)
    op.alter_column('engagements', 'filing_deadline',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='IRS filing deadline. Auto-set from engagement_type on creation. Use extended_deadline instead if an extension has been filed.',
               existing_nullable=True)
    op.alter_column('engagements', 'firm_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index('ix_engagement_templates_is_recurring', 'engagement_templates', ['is_recurring'], unique=False)
    op.create_index('ix_documents_category', 'documents', ['category'], unique=False)
    op.create_index('ix_audit_logs_user_id', 'document_audit_logs', ['user_id'], unique=False)
    op.create_index('ix_audit_logs_firm_id', 'document_audit_logs', ['firm_id'], unique=False)
    op.create_index('ix_audit_logs_document_id', 'document_audit_logs', ['document_id'], unique=False)
    op.alter_column('contacts', 'firm_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index('ix_clients_entity_type', 'clients', ['entity_type'], unique=False)
    op.alter_column('clients', 'entity_type',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='individual | business | trust | estate',
               existing_nullable=True)
    op.alter_column('clients', 'firm_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('ix_audit_logs_firm_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
