# migrations/versions/611faa198fe7_add_platform_events.py

"""add_platform_events

Adds platform_events, the append-only log for events that belong to no firm
(network-wide findings). Sibling of behavioral_events, carrying no firm_id,
no actor columns, no created_at and no updated_at. Ruled Aug 26, 2026
(Ruling 1).

Hand written rather than autogenerated. An autogenerate against this database
emits 27 operations: the 4 below plus the 23 standing drift items, which
include a DROP of the partial unique index uq_enrollment_active_lead_sequence
that must never be applied. The autogenerated file was read in full, the drift
was confirmed to be the known inventory unchanged (23 items, no table drops),
and the file was deleted in favor of this one. Only the operations belonging to
this change appear here.

Revision ID: 611faa198fe7
Revises: b8d41c7e5a20
Create Date: 2026-08-26

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '611faa198fe7'
down_revision = 'b8d41c7e5a20'
branch_labels = None
depends_on = None


def upgrade():
    op.create_table(
        'platform_events',
        sa.Column('event_id', sa.Uuid(), nullable=False),
        sa.Column('event_type', sa.String(length=100), nullable=False),
        sa.Column('entity_type', sa.String(length=50), nullable=True),
        sa.Column('entity_id', sa.Uuid(), nullable=True),
        sa.Column(
            'occurred_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint('event_id'),
    )
    op.create_index(
        op.f('ix_platform_events_event_type'), 'platform_events', ['event_type'], unique=False
    )
    op.create_index(
        op.f('ix_platform_events_occurred_at'), 'platform_events', ['occurred_at'], unique=False
    )
    op.create_index(
        'ix_platform_events_type_time',
        'platform_events',
        ['event_type', 'occurred_at'],
        unique=False,
    )


def downgrade():
    op.drop_index('ix_platform_events_type_time', table_name='platform_events')
    op.drop_index(op.f('ix_platform_events_occurred_at'), table_name='platform_events')
    op.drop_index(op.f('ix_platform_events_event_type'), table_name='platform_events')
    op.drop_table('platform_events')
