# migrations/versions/a2b3c4d5e6f7_add_engagement_members_and_task_type.py

"""add engagement_members, and internal vs client tasks

Hand written, not autogenerated. The autogenerate run for this change
produced a file that ALSO dropped peer_network_members, peer_network_rooms,
peer_network_messages, peer_network_aliases and archive_stars, because those
five models are not imported in migrations/env.py and therefore never
register with Base.metadata. Autogenerate correctly concluded they exist in
the database but not in the model layer, and proposed deleting them. That
file was discarded whole. This one contains only the four intended changes:

  1. create engagement_members
  2. tasks.task_type            (new, defaults every existing row to 'client')
  3. tasks.is_self_created      (new, defaults every existing row to false)
  4. tasks.client_id / tasks.engagement_id become nullable, so an INTERNAL
     task can exist with neither

Every existing task row is a client task by definition -- both columns were
NOT NULL until now -- so the 'client' server default backfills correctly with
no data migration step. is_self_created backfills to false because it cannot
be reconstructed after the fact: tasks has no created_by column, so there is
nothing to compare assigned_to against for a historical row. Guessing would
be worse than a truthful false.

Dropping NOT NULL is non-destructive and instant on Postgres (a catalog
change, no table rewrite). The downgrade restores NOT NULL, which will fail
if any internal task rows exist by then -- correct behavior, since silently
deleting them would be worse.

Revision ID: a2b3c4d5e6f7
Revises: z1a2b3c4d5e6
Create Date: 2026-08-08

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "a2b3c4d5e6f7"
down_revision: Union[str, Sequence[str], None] = "v9w8x7y6z5a4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "engagement_members",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("firm_id", sa.Uuid(), nullable=False),
        sa.Column("engagement_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "is_administrator",
            sa.Boolean(),
            nullable=False,
            comment=(
                "Administrator of THIS engagement only. Never implies any "
                "capability on another engagement or at the firm level."
            ),
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["engagement_id"], ["engagements.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["firm_id"], ["firms.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("engagement_id", "user_id", name="uq_engagement_member"),
    )
    op.create_index(
        op.f("ix_engagement_members_engagement_id"),
        "engagement_members",
        ["engagement_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_engagement_members_firm_id"),
        "engagement_members",
        ["firm_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_engagement_members_user_id"),
        "engagement_members",
        ["user_id"],
        unique=False,
    )

    op.add_column(
        "tasks",
        sa.Column("task_type", sa.String(length=20), server_default="client", nullable=False),
    )
    op.add_column(
        "tasks",
        sa.Column("is_self_created", sa.Boolean(), server_default="false", nullable=False),
    )
    op.create_index(op.f("ix_tasks_task_type"), "tasks", ["task_type"], unique=False)

    op.alter_column("tasks", "client_id", existing_type=sa.Uuid(), nullable=True)
    op.alter_column("tasks", "engagement_id", existing_type=sa.Uuid(), nullable=True)


def downgrade() -> None:
    # Restoring NOT NULL fails loudly if any internal task exists. That is
    # deliberate: an internal task has no client and no engagement to fall
    # back to, and deleting rows to make a downgrade succeed is not a
    # tradeoff a migration gets to make on its own.
    op.alter_column("tasks", "engagement_id", existing_type=sa.Uuid(), nullable=False)
    op.alter_column("tasks", "client_id", existing_type=sa.Uuid(), nullable=False)

    op.drop_index(op.f("ix_tasks_task_type"), table_name="tasks")
    op.drop_column("tasks", "is_self_created")
    op.drop_column("tasks", "task_type")

    op.drop_index(op.f("ix_engagement_members_user_id"), table_name="engagement_members")
    op.drop_index(op.f("ix_engagement_members_firm_id"), table_name="engagement_members")
    op.drop_index(op.f("ix_engagement_members_engagement_id"), table_name="engagement_members")
    op.drop_table("engagement_members")
