# migrations/versions/b8d41c7e5a20_drop_complexity_flags_from_engagements.py

"""drop_complexity_flags_from_engagements

Retires engagements.complexity_flags. Hand written rather than autogenerated:
an autogenerate against this database emits 24 operations, 23 of which are the
standing drift inventory, including a DROP of the partial unique index
uq_enrollment_active_lead_sequence that must never be applied. Only the one
operation below belongs to this change.

WHY THE COLUMN IS GOING. Its only writer, the complexity flags PATCH endpoint,
was cut on August 15, 2026, and the settings blob key that gated it can never
be populated again. The retirement was ruled on 0/0/0 evidence and the census
was re-run against dev immediately before writing this migration:

    total engagements                                  1
    count(complexity_flags), i.e. not SQL NULL         1
    jsonb_typeof(complexity_flags) = 'object'          0

Those first two numbers disagree with the third for the reason recorded as
instance sixteen in the process rules: jsonb can hold the JSON scalar null,
which is present rather than absent, so IS NOT NULL passes it and count()
counts it. The only surviving value is that scalar null. No real complexity
data exists in any row, so this drop destroys nothing.

Revision ID: b8d41c7e5a20
Revises: ad422a99e676
Create Date: 2026-08-23

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'b8d41c7e5a20'
down_revision = 'ad422a99e676'
branch_labels = None
depends_on = None


def upgrade():
    op.drop_column('engagements', 'complexity_flags')


def downgrade():
    # Restores the column exactly as 0039_add_complexity_flags_to_engagements
    # created it and as the live catalog reported it before the drop: jsonb,
    # nullable, no server default, same comment text. Verified against
    # information_schema and pg_description rather than inferred from the model,
    # which no longer declares it.
    op.add_column(
        'engagements',
        sa.Column(
            'complexity_flags',
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment=(
                "Complexity flags selected at engagement letter send. Keys are "
                "flag names, values are selected tier label or True for fixed flags."
            ),
        ),
    )
