"""add_findings_table

Revision ID: e0cff1ee10ea
Revises: 1e16e4b22bea
Create Date: 2026-07-09 20:13:48.634230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e0cff1ee10ea'
down_revision: Union[str, Sequence[str], None] = '1e16e4b22bea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('findings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('firm_id', sa.UUID(), nullable=True),
    sa.Column('technique', sa.String(length=100), nullable=False),
    sa.Column('subject_type', sa.Enum('metric', 'entity', 'pattern', name='subjecttype', native_enum=False), nullable=False),
    sa.Column('subject_key', sa.String(length=255), nullable=False),
    sa.Column('metric_key', sa.String(length=100), nullable=True),
    sa.Column('statistics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('data_sufficiency', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence_tier', sa.Integer(), nullable=True),
    sa.Column('gate_bar', sa.Enum('firm_facing', 'internal', name='gatebar', native_enum=False), nullable=False),
    sa.Column('gate_status', sa.Enum('pending', 'passed', 'failed', name='gatestatus', native_enum=False), nullable=False),
    sa.Column('failure_reason', sa.String(), nullable=True),
    sa.Column('severity_base_weight', sa.Numeric(), nullable=True),
    sa.Column('severity_modifiers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('severity_score', sa.Numeric(), nullable=True),
    sa.Column('lifecycle_state', sa.Enum('indexed', 'surfaced', 'displaced', 'resolved', 'dismissed', 'archived', name='findinglifecyclestate', native_enum=False), nullable=True),
    sa.Column('gate_passed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('gate_failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_recheck_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('surfaced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('displaced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dismissed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('eligible_surfaces', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('composite_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("subject_type != 'metric' OR metric_key IS NOT NULL", name='ck_findings_metric_requires_metric_key'),
    sa.ForeignKeyConstraint(['composite_id'], ['findings.id'], ),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['metric_key'], ['metric_registry.key'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_findings_failed', 'findings', ['last_recheck_at'], unique=False, postgresql_where=sa.text("gate_status = 'failed'"))
    op.create_index(op.f('ix_findings_firm_id'), 'findings', ['firm_id'], unique=False)
    op.create_index(op.f('ix_findings_gate_status'), 'findings', ['gate_status'], unique=False)
    op.create_index('ix_findings_passed', 'findings', ['firm_id', 'severity_score'], unique=False, postgresql_where=sa.text("gate_status = 'passed'"))
    op.create_index(op.f('ix_findings_technique'), 'findings', ['technique'], unique=False)
    op.create_index('uq_findings_fingerprint', 'findings', ['technique', sa.text("COALESCE(firm_id, '00000000-0000-0000-0000-000000000000'::uuid)"), 'subject_type', 'subject_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_findings_fingerprint', table_name='findings')
    op.drop_index(op.f('ix_findings_technique'), table_name='findings')
    op.drop_index('ix_findings_passed', table_name='findings', postgresql_where=sa.text("gate_status = 'passed'"))
    op.drop_index(op.f('ix_findings_gate_status'), table_name='findings')
    op.drop_index(op.f('ix_findings_firm_id'), table_name='findings')
    op.drop_index('ix_findings_failed', table_name='findings', postgresql_where=sa.text("gate_status = 'failed'"))
    op.drop_table('findings')
    # ### end Alembic commands ###
