"""add irs_authorization_warnings, drop irs_authorizations.expiry_notification_sent

Revision ID: edf14bcf2539
Revises: l1m2n3o4p5q6
Create Date: 2026-07-30 15:14:20.752041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edf14bcf2539'
down_revision: Union[str, Sequence[str], None] = 'l1m2n3o4p5q6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('irs_authorization_warnings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('firm_id', sa.Uuid(), nullable=False),
    sa.Column('authorization_id', sa.Uuid(), nullable=False),
    sa.Column('threshold_days', sa.Integer(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['authorization_id'], ['irs_authorizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('authorization_id', 'threshold_days', name='uq_irs_auth_warning_auth_threshold')
    )
    op.create_index(op.f('ix_irs_authorization_warnings_authorization_id'), 'irs_authorization_warnings', ['authorization_id'], unique=False)
    op.create_index(op.f('ix_irs_authorization_warnings_firm_id'), 'irs_authorization_warnings', ['firm_id'], unique=False)
    op.drop_column('irs_authorizations', 'expiry_notification_sent')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('irs_authorizations', sa.Column('expiry_notification_sent', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_irs_authorization_warnings_firm_id'), table_name='irs_authorization_warnings')
    op.drop_index(op.f('ix_irs_authorization_warnings_authorization_id'), table_name='irs_authorization_warnings')
    op.drop_table('irs_authorization_warnings')
    # ### end Alembic commands ###
