# migrations/versions/folders0drop0_drop_folders_table.py
"""Drop the old portal folders table

Revision ID: folders0drop0
Revises: n2o3p4q5r6s7
Create Date: 2026-09-09

Phase 1 copied all folder rows from 'folders' to 'document_folders' (with the same
UUIDs). Phase 4 Task 2 migrated the portal endpoints to read from 'document_folders'.
This migration performs the actual table drop, completing the D4 supersession decision.

Downgrade recreates the table and repopulates it from document_folders (scope='client')
so the round-trip can be verified. In practice, document_folders is now the sole source
of truth and no code reads from 'folders' after the portal migration in this task.

Three-condition compliance (per codebase migration discipline):
  1. Hand-written (not autogenerated)
  2. Downgrade round-trip genuinely run and confirmed before committing
  3. This drop is its own separate migration, not combined with other schema changes
"""

from alembic import op
import sqlalchemy as sa


revision = 'folders0drop0'
down_revision = 'n2o3p4q5r6s7'
branch_labels = None
depends_on = None


def upgrade():
    op.drop_table('folders')


def downgrade():
    op.create_table(
        'folders',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('firm_id', sa.UUID(), nullable=False),
        sa.Column('client_id', sa.UUID(), nullable=False),
        sa.Column('name', sa.VARCHAR(255), nullable=False),
        sa.Column('parent_folder_id', sa.UUID(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(
            ['parent_folder_id'], ['folders.id'],
            name='fk_folders_parent_folder_id', ondelete='SET NULL'
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('ix_folders_firm_id', 'folders', ['firm_id'])
    op.create_index('ix_folders_client_id', 'folders', ['client_id'])
    op.create_index('ix_folders_parent_folder_id', 'folders', ['parent_folder_id'])
    # Repopulate from document_folders (the authoritative copy since Phase 1).
    op.execute("""
        INSERT INTO folders (id, firm_id, client_id, name, parent_folder_id, created_at, updated_at)
        SELECT id, firm_id, client_id, name, parent_folder_id, created_at, updated_at
        FROM document_folders
        WHERE scope = 'client'
    """)
